#!/usr/bin/env python3
"""Regenerate src/Utils/UI/Assets/Icons.luau to match assets/ui-icons.png."""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

LUCIDE = pathlib.Path(__import__("os").environ.get("LUCIDE_DIR", "/tmp/lucide_direct"))
REPO = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/home/user/cobalt_optimized")

src = (LUCIDE / "source.lua").read_text()
i = src.index("local icons = {{")
j = src.index("},{", i)
names = src[i + len("local icons = {{") : j].split('","')
names[0] = names[0].lstrip('"')
names[-1] = names[-1].rstrip('"')
index_of = {n: k + 1 for k, n in enumerate(names)}
reg_start = src.index("{[48]={{", j) + len("{[48]=")
depth = 0
k = reg_start
while True:
    c = src[k]
    if c == "{":
        depth += 1
    elif c == "}":
        depth -= 1
        if depth == 0:
            break
    k += 1
entries = re.findall(r"\{(\d+),\{(\d+),(\d+)\},\{(\d+),(\d+)\}\}", src[reg_start : k + 1])

atlas_map = {}
for line in (REPO / "assets/_icon_atlas_map.txt").read_text().splitlines():
    pos, name = line.split("\t")
    atlas_map[name] = int(pos)

ordered = sorted(atlas_map.items(), key=lambda kv: kv[1])

cell_lines = []
fb_lines = []
for name, pos in ordered:
    cell_lines.append(f'\t["{name}"] = {pos},')
    sheet, w, h, x, y = (int(v) for v in entries[index_of[name] - 1])
    fb_lines.append(f'\t["{name}"] = {{ {sheet}, {x}, {y} }},')

body = '''-- Repository-local lucide icon atlas.
--
-- Cobalt used to evaluate a remote Luau module that downloaded two sprite
-- sheets while the window was starting up.  Icons are decorative, so the
-- interface must still load when neither the local atlas nor the packaged
-- sprite sheets are reachable - unknown names simply render without an icon.
--
-- `assets/ui-icons.png` is generated by tools/build_assets.py from the same
-- lucide sprite sheets the upstream module used (MIT / ISC licensed artwork);
-- `_icon_atlas_map.txt` next to it lists the cell order kept below.

local Icons = {}

export type Icon = {
	Url: string,
	ImageRectOffset: Vector2,
	ImageRectSize: Vector2,
}

local CellSize = 24
local Columns = 8
local AtlasPaths = { "assets/ui-icons.png", "Cobalt/Assets/ui-icons.png" }

-- Icon name -> 1-based cell inside the local atlas.
local IconCells: { [string]: number } = {
__CELLS__
}

-- Offline fallback geometry inside the publicly uploaded lucide sprite
-- sheets (Roblox asset ids, no HTTP request needed): name -> { sheet, x, y }.
local SheetCells: { [string]: { number } } = {
__SHEETS__
}

local SheetUrls = {
	"rbxassetid://97854828246256",
	"rbxassetid://96738291359702",
}

-- Icons are decorative: in an environment without Vector2 (or without any way
-- to reach the artwork) every lookup degrades to nil instead of throwing.
local Vector2Available = typeof(Vector2) == "table" and typeof(Vector2.new) == "function"

local function MakeIcon(Url: string, OffsetX: number, OffsetY: number): Icon?
	if not Vector2Available then
		return nil
	end

	return {
		Url = Url,
		ImageRectOffset = Vector2.new(OffsetX, OffsetY),
		ImageRectSize = Vector2.new(CellSize, CellSize),
	}
end

local AtlasUrl: string? = nil
local AtlasResolved = false

local function ResolveAtlas(): string?
	if AtlasResolved then
		return AtlasUrl
	end

	AtlasResolved = true
	if typeof(isfile) ~= "function" or typeof(getcustomasset) ~= "function" then
		return nil
	end

	for _, Path in AtlasPaths do
		local Success, Exists = pcall(isfile, Path)
		if not (Success and Exists) then
			continue
		end

		local AssetSuccess, Result = pcall(getcustomasset, Path)
		if AssetSuccess and typeof(Result) == "string" and Result ~= "" then
			AtlasUrl = Result
			return Result
		end
	end

	return nil
end

local IconCache: { [string]: Icon | false } = {}

function Icons.GetIcon(IconName: string?): Icon?
	if not IconName then
		return nil
	end

	local Cached = IconCache[IconName]
	if Cached ~= nil then
		return Cached or nil
	end

	local Cell = IconCells[IconName]
	local Url = ResolveAtlas()

	if Cell and Url then
		local ZeroBased = Cell - 1
		local ZeroBased = Cell - 1
		local Icon = MakeIcon(Url, (ZeroBased % Columns) * CellSize, math.floor(ZeroBased / Columns) * CellSize)
		if not Icon then
			IconCache[IconName] = false
			return nil
		end

		IconCache[IconName] = Icon
		return Icon
	end

	-- No local atlas: fall back to the packaged sprite sheets so icons still
	-- render on executors without filesystem access.
	local SheetCell = SheetCells[IconName]
	if SheetCell then
		local Icon = MakeIcon(SheetUrls[SheetCell[1]], SheetCell[2], SheetCell[3])
		if not Icon then
			IconCache[IconName] = false
			return nil
		end

		IconCache[IconName] = Icon
		return Icon
	end

	IconCache[IconName] = false
	return nil
end

function Icons.SetIcon(imageInstance: ImageLabel | ImageButton, IconName: string?)
	local Icon = Icons.GetIcon(IconName)
	if not Icon then
		return
	end

	if imageInstance.Image ~= Icon.Url then
		imageInstance.Image = Icon.Url
	end
	if imageInstance.ImageRectOffset ~= Icon.ImageRectOffset then
		imageInstance.ImageRectOffset = Icon.ImageRectOffset
	end
	if imageInstance.ImageRectSize ~= Icon.ImageRectSize then
		imageInstance.ImageRectSize = Icon.ImageRectSize
	end
end

return Icons
'''
body = body.replace("__CELLS__", "\n".join(cell_lines)).replace("__SHEETS__", "\n".join(fb_lines))
target = REPO / "src/Utils/UI/Assets/Icons.luau"
target.write_text(body)
print(f"wrote {target} with {len(ordered)} icons")
