#!/usr/bin/env python3
"""Emit (and optionally run) the Log capture-policy unit test.

The capture-admission valves in src/Utils/Log.luau are the difference between
"a busy game stays inspectable" and "the inspector silently empties itself",
so the policy is pinned by an executable test:

  * a burst above the per-remote valve is dropped and counted, never ignored;
  * unrelated remotes keep capturing while someone else floods;
  * the opt-in auto-ignore only engages for a remote that overflows its own
    budget across consecutive windows;
  * the global valve drops captures without touching any ignored flag.

Usage:
  python3 tools/logpolicy.py            # write build/log_policy_test.luau
  LUAU=/path/to/luau python3 tools/logpolicy.py --run
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOG_SOURCE = ROOT / "src" / "Utils" / "Log.luau"
OUTPUT = ROOT / "build" / "log_policy_test.luau"

PRELUDE = '''-- Generated by tools/logpolicy.py - do not edit.
-- Stub environment: Log.luau only needs the wax.shared surfaces it reads.
local SavedSettings = {}
local wax = { shared = {} }
wax.shared.IS_ACTOR = false
wax.shared.Connect = function(Connection) return Connection end
wax.shared.RunService = {
	Heartbeat = { Connect = function() return { Disconnect = function() end } end },
}
wax.shared.SaveManager = {
	GetState = function(_, Key, Default)
		local Value = SavedSettings[Key]
		if Value == nil then
			return Default
		end
		return Value
	end,
}
wax.shared.Settings = {}
wax.shared.Logs = { Incoming = {}, Outgoing = {} }
wax.shared.DeviceProfile = nil
wax.shared.CallFilters = nil
wax.shared.CobaltPluginManager = nil
wax.shared.ActorCommunicator = nil
wax.shared.Sonner = nil

local Log = (function()
local cloneref = function(Value) return Value end
local tick = os.clock
'''

TEST = '''
end)()

local function MakeLog(Name)
	return Log.new({ Name = Name, ClassName = "RemoteEvent" }, "Incoming", 1, nil)
end

local Spammy = MakeLog("Spammy")
local Quiet = MakeLog("Quiet")

for _ = 1, 3000 do
	Spammy:Call({ Arguments = { n = 1, "x" } })
end
for _ = 1, 10 do
	Quiet:Call({ Arguments = { n = 1, "y" } })
end

assert(#Spammy.Calls == 500, "per-remote valve should cap captures at 500, got " .. #Spammy.Calls)
assert(Spammy.SuppressedCalls > 0, "dropped spam captures must be counted")
assert(Spammy.Ignored == false, "auto-ignore off: the spammy remote must stay visible")
assert(#Quiet.Calls == 10, "quiet remote must capture every call, got " .. #Quiet.Calls)
assert(Quiet.Ignored == false, "quiet remote must never be ignored")

-- Opt-in auto-ignore engages only for the remote that sustains the overflow.
wax.shared.Settings.AutoIgnoreSpammyEvents = { Value = true }
for _ = 1, 3 do
	Spammy.SpamWindowStart = Spammy.SpamWindowStart - 2
	Quiet.SpamWindowStart = Quiet.SpamWindowStart - 2
	for _ = 1, 600 do
		Spammy:Call({ Arguments = { n = 1, "x" } })
	end
	Quiet:Call({ Arguments = { n = 1, "y" } })
end
assert(Spammy.Ignored == true, "sustained overflow must ignore the spammy remote when the setting is on")
assert(Quiet.Ignored == false, "an unrelated remote must never be ignored")

-- The global valve drops captures without touching anyone's ignored flag.
wax.shared.Settings.AutoIgnoreSpammyEvents = { Value = false }
local Flood = {}
for Index = 1, 6 do
	Flood[Index] = MakeLog("Flood" .. Index)
end
for _ = 1, 450 do
	for _, Log_ in Flood do
		Log_:Call({ Arguments = { n = 1, "f" } })
	end
end
local Victim = MakeLog("Victim")
assert(Victim:Call({ Arguments = { n = 1, "v" } }) == nil, "global valve must drop captures past the budget")
assert(Victim.Ignored == false, "global valve must never ignore an unrelated remote")
for _, Log_ in Flood do
	assert(Log_.Ignored == false, "flood remotes must not be ignored while auto-ignore is off")
end

print("log capture-policy unit test: OK")
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true", help="execute the test with $LUAU")
    args = parser.parse_args()

    source = LOG_SOURCE.read_text().replace("\r\n", "\n").strip("\n")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(PRELUDE + source + TEST)

    if not args.run:
        print(f"wrote {OUTPUT}")
        return 0

    luau = __import__("os").environ.get("LUAU")
    if not luau:
        print("LUAU is not set; wrote the test without running it")
        return 0

    result = subprocess.run([luau, str(OUTPUT)], capture_output=True, text=True)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    return result.returncode


raise SystemExit(main())
